# Generated by Django 5.2.1 on 2025-05-24 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsedresume',
            name='competence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='experience_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='parsedresume',
            name='formation_score',
            field=models.FloatField(default=0.0),
        ),
    ]
